pipeline {
   
   agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
   
    stages {
        stage('Build') {
            steps {
                sh 'mvn -DskipTests=true package'
               sh 'ls /tmp'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
               sh 'ls /tmp/'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }

stage('Sonarqube Analysis') {
            steps {
                sh 'ls /tmp/'
            }
        }

   stage('Archive') {
            steps {
                echo 'Archiving...'
               sh 'ls /tmp/'
            }
        }   

  stage('Deploy') {
            steps {
                sh './jenkins/scripts/deliver.sh'
               sh 'ls /tmp/jkgiuh'
               
            }
        }
    }
}
